import turtle 
def drawPolygon(trt, sideLength, numSides):
    turnAngle = 360 / numSides;
    for side in range(numSides):
        trt.forward(sideLength)
        trt.left(turnAngle)
x = turtle.Screen()
x.setworldcoordinates(0,0,100,100)
x = turtle.Turtle()
x.penup()
x.goto(50.5,50.5)
x.pendown()
drawPolygon(x,.5,3)
x.penup()
x.goto(50,50)
x.pendown()
drawPolygon(x,1.5,4)
x.penup()
x.goto(50,48.825)
x.pendown()
drawPolygon(x,1.5,8)
x.penup()
x.goto(50,46.85)
x.pendown()
drawPolygon(x,1.5,16)
x.penup()
x.goto(50,36)
x.pendown()
drawPolygon(x,1.5,64)
turtle.done()